### ISSUE TITLE
请求帮助

### ISSUE THREAD

**Issue by zhubinsheng** [listenfree/openwrt_k2#2]
我想请问作者有k2刷openwrt的教程吗？
还有k3c刷机的教程和固件的编译教程吗？

**Comment by listenfree** [comment]
先去安装大神的不死bootloader
https://www.right.com.cn/forum/thread-161906-1-1.html
第一次在不死bootloader breed中安装openwrt k2固件
以后可以在openwrt中直接升级

**Comment by zhubinsheng** [comment]
> 先去安装大神的不死bootloader
> https://www.right.com.cn/forum/thread-161906-1-1.html
> 第一次在不死bootloader breed中安装openwrt k2固件
> 以后可以在openwrt中直接升级

好的 感谢回复 请问您还有k3c ttl 刷机的详细教程吗

**Comment by listenfree** [comment]
不好意思，没有k3c，你可去恩山学一下

**Comment by zhubinsheng** [comment]
好的 感谢
